import { style } from '@vanilla-extract/css';
import { vars } from '../styles/obsidianTheme.css.ts';

export const page = style({ minHeight: '100vh', background: vars.color.background, color: vars.color.text });
export const main = style({ maxWidth: '720px', margin: '0 auto', padding: `0 ${vars.space.md} ${vars.space.hero}` });
export const backLink = style({ display: 'inline-flex', alignItems: 'center', gap: vars.space.xs, fontSize: '13px', color: vars.color.textMuted, marginBottom: vars.space.lg, transition: 'color 140ms ease', selectors: { '&:hover': { color: vars.color.text } } });
export const card = style({ background: vars.color.surface, border: vars.border.subtle, borderRadius: vars.radius.xl, padding: vars.space.lg });
export const cardTitle = style({ fontFamily: vars.font.display, fontSize: '24px', fontWeight: 500, marginBottom: vars.space.lg });
export const form = style({ display: 'flex', flexDirection: 'column', gap: vars.space.lg });
export const fieldLabel = style({ display: 'block', fontSize: '13px', fontWeight: 500, color: vars.color.text, marginBottom: vars.space.xs });
export const textInput = style({ width: '100%', padding: vars.space.sm, background: vars.color.surfaceSoft, border: vars.border.subtle, borderRadius: vars.radius.md, color: vars.color.text, fontSize: '14px', fontFamily: vars.font.body, outline: 'none', transition: 'border-color 160ms ease', selectors: { '&:focus': { borderColor: vars.color.accent }, '&::placeholder': { color: vars.color.textFaint } } });
export const textArea = style({ width: '100%', padding: vars.space.sm, background: vars.color.surfaceSoft, border: vars.border.subtle, borderRadius: vars.radius.md, color: vars.color.text, fontSize: '14px', fontFamily: vars.font.body, outline: 'none', resize: 'vertical', minHeight: '160px', transition: 'border-color 160ms ease', selectors: { '&:focus': { borderColor: vars.color.accent }, '&::placeholder': { color: vars.color.textFaint } } });
export const selectInput = style({ width: '100%', padding: vars.space.sm, background: vars.color.surfaceSoft, border: vars.border.subtle, borderRadius: vars.radius.md, color: vars.color.text, fontSize: '14px', fontFamily: vars.font.body, outline: 'none', cursor: 'pointer' });
export const hint = style({ fontSize: '12px', color: vars.color.textFaint, marginTop: vars.space.xs });
export const errorBox = style({ display: 'flex', alignItems: 'center', gap: vars.space.xs, background: vars.color.accentWash, color: vars.color.accent, padding: vars.space.sm, borderRadius: vars.radius.md, fontSize: '14px' });
export const submitBtn = style({ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: vars.space.xs, padding: `${vars.space.sm} ${vars.space.xl}`, background: vars.color.accent, color: vars.color.text, borderRadius: vars.radius.md, border: 'none', fontSize: '14px', fontWeight: 600, fontFamily: vars.font.body, cursor: 'pointer', transition: 'background 160ms ease', selectors: { '&:hover:not(:disabled)': { background: vars.color.accentHover }, '&:disabled': { opacity: 0.5, cursor: 'not-allowed' } } });
export const centerWrap = style({ textAlign: 'center', padding: `${vars.space.xxl} 0`, background: vars.color.surface, border: vars.border.subtle, borderRadius: vars.radius.xl });
export const centerIcon = style({ margin: `0 auto ${vars.space.sm}` });
export const centerTitle = style({ fontFamily: vars.font.display, fontSize: '20px', fontWeight: 600, marginBottom: vars.space.xs });
export const centerText = style({ color: vars.color.textMuted, fontSize: '14px', marginBottom: vars.space.md });
export const centerLink = style({ color: vars.color.accent, fontSize: '14px', transition: 'color 140ms ease', selectors: { '&:hover': { color: vars.color.text } } });
export const btnRow = style({ display: 'flex', gap: vars.space.md, justifyContent: 'center' });
export const ghostBtn = style({ display: 'inline-flex', alignItems: 'center', padding: `${vars.space.xs} ${vars.space.lg}`, background: vars.color.surfaceSoft, color: vars.color.textSoft, borderRadius: vars.radius.md, border: 'none', fontSize: '14px', fontFamily: vars.font.body, cursor: 'pointer', transition: 'all 160ms ease', selectors: { '&:hover': { background: vars.color.overlay, color: vars.color.text } } });
