import { style } from '@vanilla-extract/css';
import { vars } from '../styles/obsidianTheme.css.ts';

export const page = style({ minHeight: '100vh', background: vars.color.background, color: vars.color.text });
export const main = style({ maxWidth: '900px', margin: '0 auto', padding: `0 ${vars.space.md} ${vars.space.hero}` });
export const backLink = style({ display: 'inline-flex', alignItems: 'center', gap: vars.space.xs, fontSize: '13px', color: vars.color.textMuted, marginBottom: vars.space.lg, transition: 'color 140ms ease', selectors: { '&:hover': { color: vars.color.text } } });
export const loadingWrap = style({ display: 'flex', alignItems: 'center', justifyContent: 'center', padding: `${vars.space.xxl} 0` });
export const errorWrap = style({ textAlign: 'center', padding: `${vars.space.xxl} 0` });
export const errorIcon = style({ color: vars.color.accent, margin: `0 auto ${vars.space.sm}` });
export const errorTitle = style({ fontFamily: vars.font.display, fontSize: '20px', fontWeight: 600, marginBottom: vars.space.xs });
export const errorText = style({ color: vars.color.textMuted, fontSize: '14px', marginBottom: vars.space.md });
export const errorLink = style({ color: vars.color.accent, fontSize: '14px' });
export const questionCard = style({ background: vars.color.surface, border: vars.border.subtle, borderRadius: vars.radius.xl, padding: vars.space.lg, marginBottom: vars.space.xl });
export const questionTitle = style({ fontFamily: vars.font.display, fontSize: '28px', fontWeight: 500, letterSpacing: '-0.02em', marginBottom: vars.space.md });
export const questionMeta = style({ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: vars.space.md, fontSize: '12px', color: vars.color.textFaint, marginBottom: vars.space.lg });
export const questionContent = style({ fontSize: '15px', lineHeight: 1.8, color: vars.color.textSoft });
export const voteRow = style({ display: 'flex', alignItems: 'center', gap: vars.space.md, marginTop: vars.space.lg, paddingTop: vars.space.lg, borderTop: vars.border.subtle });
export const voteBtn = style({ display: 'inline-flex', alignItems: 'center', gap: vars.space.xxs, background: 'none', border: 'none', color: vars.color.textMuted, cursor: 'pointer', fontSize: '13px', transition: 'color 140ms ease', selectors: { '&:hover': { color: vars.color.text } } });
export const voteBtnActive = style({ color: vars.color.accent });
export const voteCount = style({ fontFamily: vars.font.label, fontSize: '14px', fontWeight: 600 });
export const answersSection = style({ marginTop: vars.space.xl });
export const answersTitle = style({ fontFamily: vars.font.display, fontSize: '24px', fontWeight: 500, marginBottom: vars.space.lg });
export const answerCard = style({ background: vars.color.surface, border: vars.border.subtle, borderRadius: vars.radius.lg, padding: vars.space.lg, marginBottom: vars.space.md });
export const answerCardAccepted = style({ borderColor: vars.color.success });
export const answerMeta = style({ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: vars.space.md, fontSize: '12px', color: vars.color.textFaint, marginBottom: vars.space.md });
export const answerContent = style({ fontSize: '14px', lineHeight: 1.8, color: vars.color.textSoft });
export const acceptedBadge = style({ display: 'inline-flex', alignItems: 'center', gap: vars.space.xxs, background: 'rgba(45,138,78,0.16)', color: vars.color.success, fontSize: '11px', fontWeight: 600, padding: `2px ${vars.space.xs}`, borderRadius: vars.radius.pill });
export const answerForm = style({ background: vars.color.surface, border: vars.border.subtle, borderRadius: vars.radius.xl, padding: vars.space.lg, marginTop: vars.space.xl });
export const answerFormTitle = style({ fontFamily: vars.font.display, fontSize: '20px', fontWeight: 500, marginBottom: vars.space.md });
export const textArea = style({ width: '100%', padding: vars.space.sm, background: vars.color.surfaceSoft, border: vars.border.subtle, borderRadius: vars.radius.md, color: vars.color.text, fontSize: '14px', fontFamily: vars.font.body, outline: 'none', resize: 'vertical', minHeight: '120px', transition: 'border-color 160ms ease', selectors: { '&:focus': { borderColor: vars.color.accent }, '&::placeholder': { color: vars.color.textFaint } } });
export const submitBtn = style({ display: 'inline-flex', alignItems: 'center', gap: vars.space.xs, padding: `${vars.space.xs} ${vars.space.lg}`, background: vars.color.accent, color: vars.color.text, borderRadius: vars.radius.md, border: 'none', fontSize: '14px', fontWeight: 600, fontFamily: vars.font.body, cursor: 'pointer', marginTop: vars.space.md, transition: 'background 160ms ease', selectors: { '&:hover:not(:disabled)': { background: vars.color.accentHover }, '&:disabled': { opacity: 0.5, cursor: 'not-allowed' } } });
export const tag = style({ display: 'inline-block', padding: `2px ${vars.space.xs}`, background: vars.color.surfaceSoft, borderRadius: vars.radius.sm, fontSize: '11px', color: vars.color.textFaint });
export const statIcon = style({ display: 'inline-flex', alignItems: 'center', gap: '3px' });
